#! /bin/sh
# Starts and stops Adsplayer
# /etc/init.d/AdsPlayer
### BEGIN INIT INFO
# Provides:     Floating ADs
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    adsplayer
### END INIT INFO
#Load up anuncios when called
case "$1" in

start)
        echo "Starting AdsPlayer..."
        cd /home/uslu/melibs_r/;
        #sudo sh -c "TERM=linux setterm -foreground black -clear all >/dev/tty0";
        sudo screen -dmS anuncios bash video.signal.sh;
;;

stop)
        echo "Stopping AdsPlayer..."
        sudo screen -S anuncios -X quit;
        #sudo killall omxplayer;
        #sudo dd if=/dev/zero of=/dev/fb0;
;;

restart)
        echo "Restarting AdsPlayer..."
        $0 stop
        $0 start
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
