#! /bin/sh
# Starts and stops Imgplayer
# /etc/init.d/ImgPlayer
### BEGIN INIT INFO
# Provides:     Imagen Flotante
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    imgplayer
### END INIT INFO
#Load up anuncios when called
case "$1" in

start)
        echo "Starting ImgPlayer..."
        cd /home/uslu/melibs_r/;
        #sudo sh -c "TERM=linux setterm -foreground black -clear all >/dev/tty0";
        sudo screen -dmS img_flotantes bash img_signal.sh;
;;

stop)
        echo "Stopping ImgPlayer..."
        sudo screen -S img_flotantes -X quit;
        #sudo killall omxplayer;
        #sudo dd if=/dev/zero of=/dev/fb0;
;;

restart)
        echo "Restarting ImgPlayer..."
        $0 stop
        $0 start
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
